GET http://localhost:8000/products/?name__icontains=tel HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###


DELETE  http://localhost:8000/products/1/ HTTP/1.1

###

PUT  http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3Mzk4ODUwLCJpYXQiOjE3NzczOTg1NTAsImp0aSI6ImM3NWQ4MjlmNWVmZjRiYjg5NDkzNDVhYTczOWI0MTAyIiwidXNlcl9pZCI6IjIifQ.tyhvBvc1J3HbRa_lzp7Xz4mGrKaOIkoOrC2jLQHZBSw

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

# Login api
POST  http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json


{
    "username": "Hari",
    "password": "1234567890"
}


###

GET   http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NjMzOTc5LCJpYXQiOjE3Nzc2MzM2NzksImp0aSI6IjJkZWQ4MzIyZjM5MjQzN2Y4YjhlZWEyM2I2YzE4MzQ5IiwidXNlcl9pZCI6IjIifQ.LVNAarm8vLtKfILirxy19kJlIARsBuEk7GZoBldl1d0


### 

POST  http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json


{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NzUzNzkyNywiaWF0IjoxNzc3NDUxNTI3LCJqdGkiOiI4NjM3ZTIxN2M5NWU0MTYzYjJlZDRhZmJlNWY5ZTQ4MiIsInVzZXJfaWQiOiIyIn0.G9oFZef5faR4ow3JEaIJLiwHvf63y_tkJWYZOoDe3cU"
}


###

GET  http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NjMzODA3LCJpYXQiOjE3Nzc2MzM1MDcsImp0aSI6ImNhOTY4MTBiYmQwMTQxYzM5ZjAwZDhlNzlkZGNmMDM0IiwidXNlcl9pZCI6IjIifQ.fXo0CIWfqMMFu_e3XuXUVJDIK1j-CbAJOQWdTbexg5w


### 

POST   http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NjE3NzAwLCJpYXQiOjE3Nzc2MTc0MDAsImp0aSI6IjYyOGJiZTM4ZTE1NDQxZmVhMmE3ZDE2ZDY4ZTUzY2Y1IiwidXNlcl9pZCI6IjIifQ.q33FvZkDbGPP67S5FH1TVmGpNtZcNTeY77mB1ibD3BQ

{
    "status": "pending",
    "items": [
        {
            "product": 2,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}


###

PUT    http://localhost:8000/orders/f185c764-382c-4a1d-93d5-f726a43dda3b/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NjIwMDIwLCJpYXQiOjE3Nzc2MTk3MjAsImp0aSI6ImVlZjdjYTg3MDgxYTRkZDViNjMzNTY0MjI4N2EwODg2IiwidXNlcl9pZCI6IjIifQ.7lBAZlJlOcKLpPlkLdpJdm7rQn_HRABt8ZkMCcm9fBs

{
    "status": "pending",
    "items": [
        {
            "product": 2,
            "quantity": 3
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

DELETE    http://localhost:8000/orders/f185c764-382c-4a1d-93d5-f726a43dda3b/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NjIwMDIwLCJpYXQiOjE3Nzc2MTk3MjAsImp0aSI6ImVlZjdjYTg3MDgxYTRkZDViNjMzNTY0MjI4N2EwODg2IiwidXNlcl9pZCI6IjIifQ.7lBAZlJlOcKLpPlkLdpJdm7rQn_HRABt8ZkMCcm9fBs
